// v4.6.8 boundary editor GUI
(function(){
'use strict';
if(window.__ONGA_BOUNDARY_EDITOR_V468__)return;window.__ONGA_BOUNDARY_EDITOR_V468__=true;
const V='onga-boundary-editor-v4.6.8',KEY='onga_boundary_editor_v468',APPLY='onga_boundary_editor_v468_applied';
const C=typeof clamp==='function'?clamp:((v,a,b)=>Math.max(a,Math.min(b,v))),R=d=>d*Math.PI/180;
const css='.ongaBoundaryEditor{position:absolute;left:12px;top:72px;z-index:90;width:min(390px,calc(100vw - 24px));background:rgba(5,12,20,.90);border:1px solid rgba(255,255,255,.18);border-radius:16px;padding:10px 11px;color:#eef;box-shadow:0 14px 40px rgba(0,0,0,.36);backdrop-filter:blur(12px);font-size:12px;line-height:1.42}.ongaBoundaryEditor.collapsed .body{display:none}.ongaBoundaryEditor h3{margin:0 0 7px;font-size:13px;display:flex;justify-content:space-between;gap:8px;align-items:center}.ongaBoundaryEditor .mini{font-size:11px;color:#a9bbce}.ongaBoundaryEditor .buttons{display:flex;flex-wrap:wrap;gap:5px;margin:6px 0}.ongaBoundaryEditor button{min-height:30px;padding:5px 8px;border-radius:10px;font-size:11px}.ongaBoundaryEditor button.active{background:rgba(91,212,255,.25);border-color:rgba(91,212,255,.65)}.ongaBoundaryEditor textarea{width:100%;height:88px;border-radius:10px;background:#07111d;color:#dff7ff;border:1px solid rgba(255,255,255,.18);font-size:11px;padding:6px;box-sizing:border-box}@media(max-width:820px){.ongaBoundaryEditor{top:58px;left:8px;right:8px;width:auto;max-height:42vh;overflow:auto}}';
function def(){return{land:[],bridge:[],barrage:[],version:V,updatedAt:null}}function load(){try{return{...def(),...(JSON.parse(localStorage.getItem(KEY)||'{}'))}}catch(e){return def()}}function save(){ed.data.updatedAt=new Date().toISOString();ed.data.version=V;localStorage.setItem(KEY,JSON.stringify(ed.data));}
const ed={active:false,mode:'land',cur:[],data:load(),applied:localStorage.getItem(APPLY)==='1',panel:null,status:null,ta:null};
const prev={mask:typeof calibratedWaterMaskValueAt==='function'?calibratedWaterMaskValueAt:null,known:typeof isKnownWater==='function'?isKnownWater:null,hydro:typeof nearestHydroCorridor==='function'?nearestHydroCorridor:null,find:typeof findLandCastPositionForWater==='function'?findLandCastPositionForWater:null,spots:typeof makeShoreCastingHotspots==='function'?makeShoreCastingHotspots:null,render:typeof renderAll==='function'?renderAll:null,bind:typeof bindUI==='function'?bindUI:null,waterStatus:typeof updateWaterStatus==='function'?updateWaterStatus:null};
function ref(){return(typeof GSI!=='undefined'&&GSI.center)?GSI.center:{lat:33.892724,lng:130.67422}}function xy(lat,lng){const r=ref();return{x:(lng-r.lng)*111320*Math.cos(R(r.lat)),y:(lat-r.lat)*110540}}function hav(a,b,c,d){if(typeof haversine==='function')return haversine(a,b,c,d);const p1=R(a),p2=R(c),d1=R(c-a),d2=R(d-b),x=Math.sin(d1/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(d2/2)**2;return 12742000*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function closed(p){if(p.length<3)return p;const a=p[0],b=p[p.length-1];return hav(a[0],a[1],b[0],b[1])<1?p.slice():p.concat([[a[0],a[1]]])}
function inside(lat,lng,poly){let inn=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const yi=poly[i][0],xi=poly[i][1],yj=poly[j][0],xj=poly[j][1];if(((yi>lat)!==(yj>lat))&&(lng<(xj-xi)*(lat-yi)/(yj-yi||1e-12)+xi))inn=!inn}return inn}
function ori(a,b,c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x)}function on(a,b,c){return Math.min(a.x,b.x)<=c.x&&c.x<=Math.max(a.x,b.x)&&Math.min(a.y,b.y)<=c.y&&c.y<=Math.max(a.y,b.y)}function cross(a,b,c,d){const A=xy(a[0],a[1]),B=xy(b[0],b[1]),C1=xy(c[0],c[1]),D=xy(d[0],d[1]),o1=ori(A,B,C1),o2=ori(A,B,D),o3=ori(C1,D,A),o4=ori(C1,D,B);return((o1>0&&o2<0||o1<0&&o2>0)&&(o3>0&&o4<0||o3<0&&o4>0))||(Math.abs(o1)<1e-9&&on(A,B,C1))||(Math.abs(o2)<1e-9&&on(A,B,D))||(Math.abs(o3)<1e-9&&on(C1,D,A))||(Math.abs(o4)<1e-9&&on(C1,D,B))}
function hitLine(a,b,arr){for(const l of arr||[])for(let i=0;i<l.length-1;i++)if(cross(a,b,l[i],l[i+1]))return true;return false}function castBlock(a,b,c,d){return hitLine([a,b],[c,d],ed.data.bridge)||hitLine([a,b],[c,d],ed.data.barrage)||!!(window.ONGA_SPATIAL_SAFETY&&window.ONGA_SPATIAL_SAFETY.castBlock&&window.ONGA_SPATIAL_SAFETY.castBlock(a,b,c,d))}
function hasLand(){return ed.applied&&ed.data.land&&ed.data.land.length}function mask(lat,lng){if(!hasLand())return prev.mask?prev.mask(lat,lng):0;if(typeof isWithinBounds==='function'&&!isWithinBounds(lat,lng))return 0;if(typeof GSI!=='undefined'&&GSI.bounds){const b=GSI.bounds;if(lat<b.south||lat>b.north||lng<b.west||lng>b.east)return 0}for(const p of ed.data.land)if(p.length>=3&&inside(lat,lng,p))return 0;return 1}
function samples(){const out=[];for(const poly of ed.data.land){const p=closed(poly);for(let i=0;i<p.length-1;i++){const a=p[i],b=p[i+1],d=hav(a[0],a[1],b[0],b[1]),n=Math.max(1,Math.ceil(d/6));for(let k=0;k<=n;k++){const t=k/n;out.push({lat:a[0]+(b[0]-a[0])*t,lng:a[1]+(b[1]-a[1])*t})}}}return out}
function nearest(target){if(!hasLand())return prev.find?prev.find(target):null;if(!target||!Number.isFinite(target.lat)||!Number.isFinite(target.lng))return null;const maxM=(typeof CAST_MODEL!=='undefined'&&CAST_MODEL.maxM)||100;let best=null;for(const s of samples()){const d=hav(s.lat,s.lng,target.lat,target.lng);if(d<2||d>maxM||castBlock(s.lat,s.lng,target.lat,target.lng))continue;const sc=(target.score||0)*(.7+.3*Math.exp(-.5*((d-35)/32)**2));if(!best||sc>best.score)best={lat:s.lat,lng:s.lng,distanceM:d,bearing:0,landConfidence:1,bankQuality:1,score:sc,onEditedBoundary:true}}return best}
function apply(){if(typeof calibratedWaterMaskValueAt==='function')calibratedWaterMaskValueAt=mask;if(typeof isKnownWater==='function')isKnownWater=(a,b)=>mask(a,b)>.5;if(typeof nearestHydroCorridor==='function')nearestHydroCorridor=(a,b)=>mask(a,b)>.5?(prev.hydro&&prev.hydro(a,b)||{kind:'edited_water',label:'編集水面',s:.5,tributaryProgress:.5,signedDistancePx:0,distancePx:0,widthPx:80,maxDistPx:140,corridor:1,seed:.75}):null;if(typeof findLandCastPositionForWater==='function')findLandCastPositionForWater=nearest;if(typeof makeShoreCastingHotspots==='function')makeShoreCastingHotspots=function(cands,n=8){if(!hasLand()&&prev.spots)return prev.spots(cands,n);const sorted=[...(cands||[])].filter(p=>p&&Number.isFinite(p.score)&&p.score>.35).sort((a,b)=>b.score-a.score),raw=[];for(let i=0;i<Math.min(sorted.length,1200);i++){const t=sorted[i],s=nearest(t);if(!s)continue;raw.push({...t,lat:s.lat,lng:s.lng,targetLat:t.lat,targetLng:t.lng,targetScore:t.score,castDistanceM:s.distanceM,landConfidence:1,bankQuality:1,onLand:true,onEditedBoundary:true,score:C(s.score,0,1),structureName:`編集境界釣り座：${t.structureName||t.hydroLabel||'水面標的'}`,reason:`編集した境界上に配置 / ${Math.round(s.distanceM)}m先の水面標的 / ${t.reason||''}`})}raw.sort((a,b)=>b.score-a.score);return raw.slice(0,n).map((h,i)=>({...h,rank:i+1,score100:Math.round((h.score||0)*100),targetScore100:Math.round((h.targetScore||h.score||0)*100)}))}}
function gj(){const fs=[];ed.data.land.forEach((p,i)=>fs.push({type:'Feature',properties:{kind:'land_polygon',id:`land_${i}`},geometry:{type:'Polygon',coordinates:[closed(p).map(q=>[q[1],q[0]])]}}));ed.data.bridge.forEach((l,i)=>fs.push({type:'Feature',properties:{kind:'bridge',id:`bridge_${i}`},geometry:{type:'LineString',coordinates:l.map(q=>[q[1],q[0]])}}));ed.data.barrage.forEach((l,i)=>fs.push({type:'Feature',properties:{kind:'barrage',id:`barrage_${i}`},geometry:{type:'LineString',coordinates:l.map(q=>[q[1],q[0]])}}));return{type:'FeatureCollection',name:'onga_boundary_editor_export',features:fs}}
function from(obj){const d=def();for(const f of obj.features||[]){const k=f.properties?.kind||'',g=f.geometry||{};if(g.type==='Polygon'&&/land/.test(k)){const r=(g.coordinates?.[0]||[]).map(c=>[c[1],c[0]]);if(r.length>=4)d.land.push(r)}else if(g.type==='LineString'){const l=(g.coordinates||[]).map(c=>[c[1],c[0]]);if(/barrage/.test(k))d.barrage.push(l);else if(/bridge/.test(k))d.bridge.push(l)}}return d}
function status(){if(ed.status)ed.status.textContent=`mode=${ed.mode} land=${ed.data.land.length} bridge=${ed.data.bridge.length} barrage=${ed.data.barrage.length} current=${ed.cur.length} applied=${ed.applied?'ON':'OFF'}`;if(ed.ta)ed.ta.value=JSON.stringify(gj(),null,2)}function complete(){if(ed.cur.length<2)return;if(ed.mode==='land'&&ed.cur.length>=3)ed.data.land.push(closed(ed.cur));else if(ed.mode==='bridge')ed.data.bridge.push(ed.cur.slice());else if(ed.mode==='barrage')ed.data.barrage.push(ed.cur.slice());ed.cur=[];save();status();renderAll()}function undo(){if(ed.cur.length)ed.cur.pop();else ed.data[ed.mode].pop();save();status();renderAll()}function clearAll(){if(!confirm('境界編集データを全削除しますか？'))return;ed.data=def();ed.cur=[];ed.applied=false;localStorage.removeItem(KEY);localStorage.removeItem(APPLY);status();renderAll()}function applyEdited(){ed.applied=true;localStorage.setItem(APPLY,'1');apply();try{state.waterSampleCache?.clear?.();state.fluidCache?.clear?.();state.fluidBaseCache?.clear?.();state.validationCache?.clear?.();state.timeline?.length&&typeof computeAndRender==='function'?computeAndRender(true):renderAll()}catch(e){}status()}function dl(){const u=URL.createObjectURL(new Blob([JSON.stringify(gj(),null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=u;a.download='onga_boundary_editor.geojson';a.click();URL.revokeObjectURL(u)}function imp(){try{ed.data=from(JSON.parse(ed.ta.value));ed.cur=[];save();status();renderAll()}catch(e){alert('GeoJSON読込失敗: '+e.message)}}
function btn(t,f,act){const b=document.createElement('button');b.textContent=t;b.type='button';if(act)b.classList.add('active');b.onclick=f;return b}function panel(){if(ed.panel)return;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);const p=document.createElement('div');p.className='ongaBoundaryEditor collapsed';p.innerHTML='<h3><span>水面・陸地境界 編集</span><button type="button" class="fold">開く</button></h3><div class="body"><div class="mini">緑=閉じた陸地ポリゴン（外側が水面） / 黄=橋 / 赤=河口堰。ON中は地図クリックで点追加。</div><div class="buttons modes"></div><div class="buttons acts"></div><div class="mini stat"></div><textarea spellcheck="false"></textarea></div>';document.body.appendChild(p);ed.panel=p;ed.status=p.querySelector('.stat');ed.ta=p.querySelector('textarea');p.querySelector('.fold').onclick=()=>{p.classList.toggle('collapsed');p.querySelector('.fold').textContent=p.classList.contains('collapsed')?'開く':'閉じる'};const m=p.querySelector('.modes'),a=p.querySelector('.acts');[['land','緑:陸地境界'],['bridge','黄:橋'],['barrage','赤:河口堰']].forEach(x=>{const b=btn(x[1],()=>{ed.mode=x[0];[...m.children].forEach(c=>c.classList.toggle('active',c.dataset.m===ed.mode));status()},x[0]===ed.mode);b.dataset.m=x[0];m.appendChild(b)});a.append(btn('編集ON/OFF',()=>{ed.active=!ed.active;status();renderAll()}));a.append(btn('線を確定',complete));a.append(btn('戻す',undo));a.append(btn('保存',()=>{save();status()}));a.append(btn('計算に適用',applyEdited));a.append(btn('GeoJSON出力',dl));a.append(btn('GeoJSON読込',imp));a.append(btn('全削除',clearAll));status()}
function handlers(){const c=state?.canvas||document.getElementById('mapCanvas');if(!c||c.dataset.boundaryEditorV468)return;c.dataset.boundaryEditorV468='1';c.addEventListener('pointerdown',e=>{if(!ed.active)return;e.preventDefault();e.stopImmediatePropagation();const ll=canvasToLatLng(e.offsetX,e.offsetY);ed.cur.push([ll.lat,ll.lng]);status();renderAll()},true);c.addEventListener('dblclick',e=>{if(!ed.active)return;e.preventDefault();e.stopImmediatePropagation();complete()},true)}function drawLine(ctx,l,col,w=2,fill=false){if(!l||!l.length)return;ctx.beginPath();l.forEach((q,i)=>{const p=latLngToCanvas(q[0],q[1]);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});if(fill){ctx.closePath();ctx.fillStyle='rgba(0,0,0,.30)';ctx.fill()}ctx.strokeStyle=col;ctx.lineWidth=w;ctx.stroke()}function overlay(ctx){if(!ctx||typeof latLngToCanvas!=='function')return;ctx.save();for(const p of ed.data.land)drawLine(ctx,p,'rgba(0,255,120,.92)',2.8,true);for(const l of ed.data.bridge)drawLine(ctx,l,'rgba(255,220,50,.96)',4);for(const l of ed.data.barrage)drawLine(ctx,l,'rgba(255,60,60,.96)',4);drawLine(ctx,ed.cur,ed.mode==='land'?'rgba(0,255,120,.98)':ed.mode==='bridge'?'rgba(255,220,50,.98)':'rgba(255,60,60,.98)',2.5,false);if(ed.active){ctx.fillStyle='rgba(5,12,20,.75)';ctx.fillRect(12,state.height-35,335,24);ctx.fillStyle='#eaf7ff';ctx.font='12px -apple-system,sans-serif';ctx.fillText('境界編集ON：クリックで点追加、ダブルクリックで線確定',20,state.height-18)}ctx.restore()}
if(prev.render)renderAll=function(){const r=prev.render.apply(this,arguments);try{overlay(state.ctx)}catch(e){}return r};if(prev.bind)bindUI=function(){const r=prev.bind.apply(this,arguments);panel();handlers();return r};else setTimeout(()=>{panel();handlers()},500);if(prev.waterStatus)updateWaterStatus=function(){const r=prev.waterStatus.apply(this,arguments),el=document.getElementById('waterStatus');if(el&&!el.textContent.includes('境界編集GUI'))el.textContent+=' / v4.6.8: 境界編集GUI';return r};apply();window.ONGA_BOUNDARY_EDITOR={version:V,editor:ed,toGeoJSON:gj,applyEdited,waterMaskValueAt:mask};
})();
